version: "2"
services:



  # Agent
  oc-agent:
    image: ocagent:latest
    command: ["--config=/etc/oc-agent-config.yaml", "--http-pprof-port=1888"]
    volumes:
      - ./oc-agent-config.yaml:/etc/oc-agent-config.yaml
    ports:
      - "1888:1888"
      - "14268"
      - "55678:55678"
      - "55679:55679"
    network_mode: "host"
