version: "2"
services:

  # Collector
  oc-collector:
    image: occollector:latest
    command: ["--config=/etc/oc-collector-config.yaml", "--http-pprof-port=1777"]
    volumes:
      - ./oc-collector-config.yaml:/etc/oc-collector-config.yaml
    ports:
      - "55678"
      - "55680:55679"
      - "1777:1777"
      - "8888:8888" # Prometheus metrics
    depends_on:
      - kafka

  # Agent
  oc-agent:
    image: ocagent:latest
    command: ["--config=/etc/oc-agent-config.yaml", "--http-pprof-port=1888"]
    volumes:
      - ./oc-agent-config.yaml:/etc/oc-agent-config.yaml
    ports:
      - "1888:1888"
      - "14268"
      - "55678:55678"
      - "55679:55679"
    depends_on:
      - oc-collector

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      KAFKA_LISTENERS: OUTSIDE://:9091,INSIDE://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:9091,INSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "cluster-spans:1:1,cluster-dump-spans:1:1" 
      
